create table if not exists chats (
    id bigint primary key
);

create table if not exists links (
    id bigint generated by default as identity primary key,
    url text not null unique,
    tags text not null default '',
    "filters" text not null default '',
    last_updated_at timestamp with time zone not null
);

create table if not exists chat_links (
                                          chat_id bigint not null references chats(id) on delete cascade,
    link_id bigint not null references links(id) on delete cascade,
    primary key (chat_id, link_id)
    );

create index if not exists idx_chat_links_link_id on chat_links(link_id);
