create table if not exists chats (
    id bigint primary key
);

create table if not exists links (
    id bigint generated by default as identity primary key,
    url text not null unique,
    tags text not null default '',
    "filters" text not null default '',
    last_updated_at timestamp with time zone not null
);

create table if not exists chat_links (
    chat_id bigint not null references chats(id) on delete cascade,
    link_id bigint not null references links(id) on delete cascade,
    primary key (chat_id, link_id)
);

create index if not exists idx_chat_links_link_id on chat_links(link_id);
create index if not exists idx_links_last_updated_at on links(last_updated_at);

create table if not exists outbox_events (
    id uuid primary key default gen_random_uuid(),
    aggregate_id bigint not null,
    event_type varchar(100) not null,
    payload jsonb not null,
    created_at timestamptz not null default now(),
    published_at timestamptz,
    retry_count int not null default 0
);

create index if not exists idx_outbox_unpublished on outbox_events(created_at) where published_at is null;
